freq: D

metric: smape

resample: false

train_predict_ratio: 1

accelerator: cpu

group_col: group_id

backtest_periods: 38

static_features:
  #- State

dynamic_future:
  #- Open
  #- Promo
  #- DayOfWeek

dynamic_historical:

active_models:
  - StatsForecastBaselineWindowAverage
  - StatsForecastBaselineSeasonalWindowAverage
  - StatsForecastBaselineNaive
  - StatsForecastBaselineSeasonalNaive
  - StatsForecastAutoArima
  - StatsForecastAutoETS
  - StatsForecastAutoCES
  - StatsForecastAutoTheta
  - StatsForecastTSB
  - StatsForecastADIDA
  - StatsForecastIMAPA
  - StatsForecastCrostonClassic
  - StatsForecastCrostonOptimized
  - StatsForecastCrostonSBA

#Here we can override hyperparameters for built-in models
models:

  StatsForecastBaselineWindowAverage:
    model_spec:
      window_size: 7

  StatsForecastBaselineSeasonalWindowAverage:
    model_spec:
      season_length: 7
      window_size: 7

  StatsForecastBaselineSeasonalNaive:
    model_spec:
      season_length: 7

  StatsForecastAutoArima:
    model_spec:
      season_length: 7
      approximation:
      level:

  StatsForecastAutoETS:
    model_spec:
      season_length: 7
      model: "ZNZ"

  StatsForecastAutoCES:
    model_spec:
      season_length: 7
      model: "Z"

  StatsForecastAutoTheta:
    model_spec:
      season_length: 7
      decomposition_type: "multiplicative"

