services:
  spark-master:
    container_name: da-spark-master
    build:
      context: ..
      dockerfile: spark-setup/Dockerfile
    image: forecast-forge-spark:latest
    command: ["master"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ../:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'


  spark-history-server:
    container_name: da-spark-history
    image: forecast-forge-spark:latest
    command: ["history"]
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

  spark-worker:
#    container_name: da-spark-worker
    image: forecast-forge-spark:latest
    command: ["worker"]
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ../:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs:
